language: node_js
node_js:
  - '12.15.0'
services:
  - docker
cache: yarn
branches:
  only:
    - master
script:
  - yarn lint
  - yarn test
after_success:
  - yarn coverage:coveralls
  - bash deploy.sh
  - bin/ecs_deploy.sh
