language: node_js
node_js:
  - '12.15.0'
services:
  - docker
branches:
  only:
    - master
    - development
    - debug-jest
cache:
  directories:
    - node_modules
  yarn: true
script:
  - yarn lint
  - yarn coverage:coveralls
after_success:
  - bash deploy.sh
  - bash ecs_deploy.sh
