language: node_js
node_js:
  - '12.15.0'
services:
  - mongodb
cache: yarn
branches:
  only:
    - master
env:
  global:
    - PORT=9000
    - MONGODB_URL=mongodb://localhost:27017/home-automation
    - JWT_SECRET=asfbhjsdnfacgbqledfn@#$dshbabb*(@^*ksas
    - JWT_ACCESS_EXPIRATION_MINUTES=30
    - JWT_REFRESH_EXPIRATION_DAYS=30
script:
  - yarn lint
  - yarn test
after_success: yarn coverage:coveralls
