language: node_js
node_js:
  - '12.15.0'
services:
  - docker
cache: yarn
branches:
  only:
    - master
script:
  - yarn lint
  - yarn test
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
after_success:
  - yarn coverage:coveralls
